pr:
  - master

variables:
  API_KEY: $(apiKey)

jobs:
  - job: terraform_plan_json
    displayName: Terraform plan JSON
    pool:
      vmImage: ubuntu-latest

    steps:
      - task: InfracostSetup@0
        inputs:
          apiKey: 'asdf'
          version: '0.9.x'