on:
  push:
    tags:
      - "v*"
name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build project
        run: |
          make release

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "true"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "none"
          ALLOW_EMPTY_CHANGELOG: "true"
          RELEASE_NAME_PREFIX: "Release "
        with:
          args: |
            ./build/*.tar.gz
            ./build/*.sha256
            ./docs/generated/docs.tar.gz